// <auto-generated />
using FFCDemoPaymentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FFCDemoPaymentService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200120120215_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FFCDemoPaymentService.Models.Payment", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnName("claimId")
                        .HasColumnType("text");

                    b.Property<decimal>("Decimal")
                        .HasColumnName("value")
                        .HasColumnType("numeric");

                    b.HasKey("ClaimId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("FFCDemoPaymentService.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("scheduleId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimId")
                        .HasColumnName("claimId")
                        .HasColumnType("text");

                    b.Property<decimal>("Decimal")
                        .HasColumnName("value")
                        .HasColumnType("numeric");

                    b.HasKey("ScheduleId");

                    b.ToTable("schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
