version: '3.7'
services: 
  ffc-demo-payment-service-core: 
    entrypoint: ["dotnet", "watch", "test"]
    volumes: 
      - ./FFCDemoPaymentService:/app/FFCDemoPaymentService
      - ./FFCDemoPaymentService.Tests:/app/FFCDemoPaymentService.Tests
