version: '3.7'
services: 
  ffc-demo-payment-service-core: 
    build: 
      context: .
      target: development
    depends_on: 
      - ffc-demo-payment-core-postgres
      - ffc-demo-payment-message-queue
    environment: 
      ConnectionStrings__DefaultConnection: "Server=ffc-demo-payment-core-postgres;Port=5432;Database=ffc_demo_payments;User Id=postgres;Password=ppp;"
    volumes: 
      - ./FFCDemoPaymentService:/FFCDemoPaymentService

  ffc-demo-payment-core-postgres:
    image: postgres:11.4-alpine
    environment: 
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data: {}
