version: '3.7'

# This override file should be used to run automated tests in a
# containerised environment.

services:
  ffc-demo-payment-service-core:
    build:
      target: development
    image: ffc-demo-payment-service-core-development
    container_name: ffc-demo-payment-service-core-test
    entrypoint: dotnet test ./FFCDemoPaymentService.Tests/FFCDemoPaymentService.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'
    volumes: 
      - ./test-output/:/home/dotnet/FFCDemoPaymentService.Tests/test-output/
