version: '3.7'
services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service-core
    container_name: ffc-demo-payment-service-core
    depends_on:
      - ffc-demo-payment-core-postgres
      - ffc-demo-payment-artemis-queue
    environment:      
      ConnectionStrings__DefaultConnection: "Server=ffc-demo-payment-core-postgres;Port=5432;Database=ffc_demo_payments;User Id=postgres;Password=ppp;"
      Messaging__ScheduleQueueName: "schedule"
      Messaging__PaymentQueueName: "payment"
      Messaging__MessageQueueHost: "ffc-demo-payment-artemis-queue"
      Messaging__MessageQueuePort: "5672"
      Messaging__MessageQueuePreFetch: "5"
      Messaging__MessageQueueUser: "artemis"
      Messaging__MessageQueuePassword: "artemis"

  ffc-demo-payment-core-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-demo-payment-artemis-queue:
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis

volumes:
  postgres_data: {}
