version: '3.7'
services:
  ffc-demo-payment-artemis-queue:
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "8161:8161"
      - "5672:5672"
