version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-payment-service-core:
    build:
      target: development
    image: ffc-demo-payment-service-core-development
    depends_on:
      - ffc-demo-payment-message-queue
    environment:
      Messaging__Host: ffc-demo-payment-message-queue
      Messaging__ScheduleQueueEndpoint: http://ffc-demo-payment-message-queue:9324
      Messaging__PaymentQueueEndpoint: http://ffc-demo-payment-message-queue:9324
    ports:
      - "3007:3007"
    volumes:
      - ./FFCDemoPaymentService/:/home/dotnet/FFCDemoPaymentService/
      - ./FFCDemoPaymentService.Tests/:/home/dotnet/FFCDemoPaymentService.Tests/

  ffc-demo-payment-message-queue:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"

