version: '3.7'

# This file is used to copy obj files from the built container to
# the correct place on the local file system so Snyk can be run

services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: development
    image: ffc-demo-payment-service-core-snyk
    command: -c "cp -r ./obj/FFCDemoPaymentService/project.assets.json ./FFCDemoPaymentService/obj/project.assets.json"
    entrypoint: /bin/sh
    volumes:
      - ./FFCDemoPaymentService/:/home/dotnet/FFCDemoPaymentService/
