version: '3.7'

# This override file should be used to run a file watcher to
# automatically execute tests whenever code is modified.

services:
  ffc-demo-payment-service-core:
    build:
      target: development
    image: ffc-demo-payment-service-core-development
    command: [ "watch", "--project", "./FFCDemoPaymentService.Tests", "test" ]
    volumes:
      - ./FFCDemoPaymentService/:/home/dotnet/FFCDemoPaymentService/
      - ./FFCDemoPaymentService.Tests/:/home/dotnet/FFCDemoPaymentService.Tests/
