version: '3.8'
services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service-core
    container_name: ffc-demo-payment-service-core
    depends_on:
      - ffc-demo-payment-core-postgres
      - sbemulator
    volumes:
      - sb_cert_data:/testca
    environment:
      ApplicationInsights__ConnectionString: ${APPINSIGHTS_CONNECTIONSTRING}
      ApplicationInsights__CloudRole: ffc-demo-payment-service-core-local
      Messaging__ScheduleTopicName: ${SCHEDULE_TOPIC_ADDRESS:-ffc-demo-schedule}${MESSAGE_QUEUE_SUFFIX}
      Messaging__ScheduleSubscriptionName: ${SCHEDULE_SUBSCRIPTION_ADDRESS:-ffc-demo-schedule-payment-core}${MESSAGE_QUEUE_SUFFIX}
      Messaging__PaymentTopicName: ${PAYMENT_TOPIC_ADDRESS:-ffc-demo-payment}${MESSAGE_QUEUE_SUFFIX}
      Messaging__PaymentSubscriptionName: ${PAYMENT_SUBSCRIPTION_ADDRESS:-ffc-demo-payment-payment-core}${MESSAGE_QUEUE_SUFFIX}
      Messaging__MessageQueueHost: ${MESSAGE_QUEUE_HOST:-sbemulator}
      Messaging__MessageQueueUser: ${MESSAGE_QUEUE_USER:-all}
      Messaging__MessageQueuePassword: ${MESSAGE_QUEUE_PASSWORD:-CLwo3FQ3S39Z4pFOQDefaiUd1dSsli4XOAj3Y9Uh1E=;EnableAmqpLinkRedirect=false}
      Postgres__PostgresUser: postgres
      Postgres__PostgresPassword: ppp
      Postgres__PostgresDb: ffc_demo_payments
      Postgres__PostgresHost: ffc-demo-payment-core-postgres
      Postgres__PostgresPort: "5432"
      Schema__Default: ${POSTGRES_SCHEMA_NAME:-public}

  ffc-demo-payment-core-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
  
  rabbit:
    image: rabbitmq:3-management
    user: rabbitmq    
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 30s
      retries: 60

  sbemulator:
    image: devopsifyme/sbemu:latest
    volumes:
      - sb_cert_data:/app      
    environment:
      - EMULATOR__RABBITMQ__HOST=rabbit
      - EMULATOR__RABBITMQ__USERNAME=guest
      - EMULATOR__RABBITMQ__PASSWORD=guest              
      - Emulator__QueuesAndTopics=test-queue;ffc-demo-schedule/Subscriptions/ffc-demo-schedule-payment-core;ffc-demo-payment/Subscriptions/ffc-demo-schedule-payment-core
    links: 
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy

volumes:
  sb_cert_data:  