version: '3.8'
services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: production
    ports:
      - "3007:3007"
    image: ffc-demo-payment-service-core
    container_name: ffc-demo-payment-service-core
    environment:
      ApplicationInsights__ConnectionString: ${APPINSIGHTS_CONNECTIONSTRING}
      ApplicationInsights__CloudRole: ffc-demo-payment-service-core-local
      Messaging__ScheduleTopicName: ${SCHEDULE_TOPIC_ADDRESS}
      Messaging__ScheduleSubscriptionName: ${SCHEDULE_SUBSCRIPTION_ADDRESS}
      Messaging__PaymentTopicName: ${PAYMENT_TOPIC_ADDRESS}
      Messaging__PaymentSubscriptionName: ${PAYMENT_SUBSCRIPTION_ADDRESS}
      Messaging__MessageQueueHost: ${MESSAGE_QUEUE_HOST}
      Messaging__MessageQueueUser: ${MESSAGE_QUEUE_USER}
      Messaging__MessageQueuePassword: ${MESSAGE_QUEUE_PASSWORD}
      Postgres__PostgresUser: sqladmin
      Postgres__PostgresPassword: ${POSTGRES_PASSWORD}
      Postgres__PostgresDb: ffc_demo_payments
      Postgres__PostgresHost: ${POSTGRES_HOST}
      Postgres__PostgresPort: "5432"
      Schema__Default: ${POSTGRES_SCHEMA_NAME:-public}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      RedisCache__RedisHost: ${REDIS_HOST}
      RedisCache__RedisPassword: ${REDIS_PASSWORD}
      RedisCache__RedisPort: ${REDIS_PORT:-6380}
      AzureStorage__AccountName: ${STORAGE_ACCOUNTNAME}
      AzureStorage__AccountKey: ${STORAGE_ACCOUNTKEY}
      AzureAppConfig__Endpoint: ${AZCONFIG_ENDPOINT}
      AzureAppConfig__Id: ${AZCONFIG_ID}
      AzureAppConfig__Secret: ${AZCONFIG_SECRET}

