version: '3.8'

# This override file should be used to run automated tests in a
# containerised environment.

services:
  ffc-demo-payment-service-core:
    build:
      target: development
    image: ffc-demo-payment-service-core-development
    container_name: ffc-demo-payment-service-core-test
    entrypoint: dotnet test ./FFCDemoPaymentService.Tests/FFCDemoPaymentService.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'
    volumes:
      - ./FFCDemoPaymentService:/home/dotnet/FFCDemoPaymentService
      - ./FFCDemoPaymentService.Tests:/home/dotnet/FFCDemoPaymentService.Tests
      - ./test-output:/home/dotnet/FFCDemoPaymentService.Tests/test-output

  ffc-demo-payment-core-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
