version: '3.7'
services:
  liquibase:
    image: liquibase/liquibase
    depends_on:
      - ffc-demo-payment-core-postgres
    entrypoint: >
      sh -c "/liquibase/liquibase
      --changeLogFile=/changelog/db.changelog-master.xml
      --url='jdbc:postgresql://host.docker.internal:5432/ffc_demo_payments'
      --username=postgres
      --password=ppp 
      --defaultSchemaName=pr1
      update"

    volumes:
      - ./changelog/:/liquibase/changelog/
  
  ffc-demo-payment-core-postgres:
    ports:
      - "5432:5432"
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
