version: '3.7'
services: 
  ffc-demo-payment-service-core-test: 
    entrypoint: ["dotnet", "watch", "test"]
    volumes: 
      - ./FFCDemoPaymentService:/FFCDemoPaymentService
      - ./FFCDemoPaymentService.Tests:/FFCDemoPaymentService.Tests