version: '3.7'
services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service-core
    container_name: ffc-demo-payment-service-core
    depends_on:
      - ffc-demo-payment-core-postgres
    environment:
      ApplicationInsights__InstrumentationKey: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      ApplicationInsights__CloudRole: ffc-demo-payment-service-core-local
      ConnectionStrings__DefaultConnection: "Server=ffc-demo-payment-core-postgres;Port=5432;Database=ffc_demo_payments;User Id=postgres;Password=ppp;"
      Messaging__ScheduleQueueName: ffc-demo-schedule-${MESSAGE_QUEUE_SUFFIX}
      Messaging__PaymentQueueName: ffc-demo-payment-${MESSAGE_QUEUE_SUFFIX}
      Messaging__MessageQueueHost: ${MESSAGE_QUEUE_HOST:-notset}
      Messaging__MessageQueuePreFetch: "5"
      Messaging__MessageQueueUser: ${MESSAGE_QUEUE_USER:-notset}
      Messaging__MessageQueuePassword: ${MESSAGE_QUEUE_PASSWORD:-notset}

  ffc-demo-payment-core-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
