version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: development
    image: ffc-demo-payment-service-core-snyk
    command: -c "cp -r ./obj/FFCDemoPaymentService/* ./FFCDemoPaymentService/obj"
    entrypoint: /bin/sh
    volumes:
      - ./FFCDemoPaymentService/:/home/dotnet/FFCDemoPaymentService/
