version: '3.8'
services:
  ffc-demo-payment-service-core:
    build:
      context: .
      target: production
    image: ffc-demo-payment-service-core
    container_name: ffc-demo-payment-service-core
    depends_on:
      - ffc-demo-payment-core-postgres
    environment:
      ApplicationInsights__InstrumentationKey: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      ApplicationInsights__CloudRole: ffc-demo-payment-service-core-local
      Messaging__ScheduleTopicName: ${SCHEDULE_TOPIC_ADDRESS:-ffc-demo-schedule}${MESSAGE_QUEUE_SUFFIX}
      Messaging__ScheduleSubscriptionName: ${SCHEDULE_SUBSCRIPTION_ADDRESS:-ffc-demo-schedule-payment-core}${MESSAGE_QUEUE_SUFFIX}
      Messaging__PaymentTopicName: ${PAYMENT_TOPIC_ADDRESS:-ffc-demo-payment}${MESSAGE_QUEUE_SUFFIX}
      Messaging__PaymentSubscriptionName: ${PAYMENT_SUBSCRIPTION_ADDRESS:-ffc-demo-payment-payment-core}${MESSAGE_QUEUE_SUFFIX}
      Messaging__MessageQueueHost: ${MESSAGE_QUEUE_HOST}
      Messaging__MessageQueueUser: ${MESSAGE_QUEUE_USER}
      Messaging__MessageQueuePassword: ${MESSAGE_QUEUE_PASSWORD}
      Postgres__PostgresUser: postgres
      Postgres__PostgresPassword: ppp
      Postgres__PostgresDb: ffc_demo_payments
      Postgres__PostgresHost: ffc-demo-payment-core-postgres
      Postgres__PostgresPort: "5432"
      Schema__Default: ${POSTGRES_SCHEMA_NAME:-public}

  ffc-demo-payment-core-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_payments
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppp
