{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-payment-service-core.config-map") -}}
{{- define "ffc-demo-payment-service-core.config-map" -}}
data:
  ApplicationInsights__CloudRole: {{ .Values.name | quote }}
  COMPlus_EnableDiagnostics: {{ .Values.container.comPlusEnableDiagnostics | quote }}
  PORT: {{ .Values.container.port | quote }}
  Messaging__ScheduleQueueName: {{ .Values.container.scheduleQueueAddress | quote }}
  Messaging__PaymentQueueName: {{ .Values.container.paymentQueueAddress | quote }}
  Messaging__MessageQueueHost: {{ .Values.container.messageQueueHost | quote }}
  Messaging__MessageQueuePreFetch: {{ .Values.container.messageQueuePreFetch | quote }}
  Postgres__PostgresDb: {{ .Values.postgresService.postgresDb | quote }}
  Postgres__PostgresHost: {{ .Values.postgresService.postgresHost | quote }}
  Postgres__PostgresPort: {{ .Values.postgresService.postgresPort | quote }}
  Schema__Default: {{ .Values.postgresService.schemaName | quote }}
{{- end -}}
