{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-payment-service-core.config-map") -}}
{{- define "ffc-demo-payment-service-core.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ quote .Values.container.comPlusEnableDiagnostics }}
  PORT: {{ quote .Values.container.port }}
  Messaging__ScheduleQueueName: {{ quote .Values.container.scheduleQueueName }}
  Messaging__PaymentQueueName: {{ quote .Values.container.paymentQueueName }}
  Messaging__MessageQueueHost: {{ quote .Values.container.messageQueueHost }}
  Messaging__MessageQueuePort: {{ quote .Values.container.messageQueuePort }}
  Messaging__MessageQueueUser: {{ quote .Values.container.messageQueueUser }}
  Messaging__MessageQueuePassword: {{ quote .Values.container.messageQueuePassword }}
{{- end -}}s