{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-payment-service-core.config-map") -}}
{{- define "ffc-demo-payment-service-core.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ quote .Values.container.comPlusEnableDiagnostics }}
  PORT: {{ quote .Values.container.port }}
  Messaging__ScheduleQueueName: {{ quote .Values.container.scheduleQueueName }}
  Messaging__ScheduleQueueEndpoint: {{ quote .Values.container.scheduleQueueEndpoint }}
  Messaging__CreateScheduleQueue: {{ quote .Values.container.scheduleCreateQueue }}
  Messaging__PaymentQueueName: {{ quote .Values.container.paymentQueueName }}
  Messaging__PaymentQueueEndpoint: {{ quote .Values.container.paymentQueueEndpoint }}
  Messaging__CreatePaymentQueue: {{ quote .Values.container.paymentCreateQueue }}
{{- end -}}