{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-payment-service-core.config-map") -}}
{{- define "ffc-demo-payment-service-core.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ quote .Values.container.comPlusEnableDiagnostics }}
  PORT: {{ quote .Values.container.port }}
  Messaging__ScheduleQueueName: {{ quote .Values.container.scheduleQueueAddress }}
  Messaging__PaymentQueueName: {{ quote .Values.container.paymentQueueAddress }}
  Messaging__MessageQueueHost: {{ quote .Values.container.messageQueueHost }}
  Messaging__MessageQueuePort: {{ quote .Values.container.messageQueuePort }}
  Messaging__MessageQueuePreFetch: {{ quote .Values.container.messageQueuePreFetch }}
  ApplicationInsights__CloudRole: {{ quote .Values.name }}
{{- end -}}
