{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service-core.container-secret") -}}
{{- define "ffc-demo-payment-service-core.container-secret" -}}
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.postgresService.paymentCoreConnectionString | quote }}
{{- end -}}
