{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service-core.container-secret") -}}
{{- define "ffc-demo-payment-service-core.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  ApplicationInsights__connectionString: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
  Postgres__PostgresPassword: {{ .Values.postgresService.postgresPassword | quote }}
  RedisCache__RedisPassword: {{ .Values.redisCacheService.redisPassword | quote }}
  AzureStorage__AccountKey: {{ .Values.azureStorageService.accountKey | quote }}
  AzureAppConfig__Secret: {{ .Values.azureAppConfigService.secret | quote }}
{{- end -}}
