{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service-core.container-secret") -}}
{{- define "ffc-demo-payment-service-core.container-secret" -}}
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.postgresService.postgresConnectionString | quote }}
  Messaging__MessageQueueUser: {{ .Values.container.messageQueueUser | quote }}
  Messaging__MessageQueuePassword: {{ .Values.container.messageQueuePassword | quote }}
{{- end -}}