{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service-core.container-secret") -}}
{{- define "ffc-demo-payment-service-core.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  ApplicationInsights__InstrumentationKey: {{ .Values.appInsights.key | quote }}
  {{- end }}
  Postgres__PostgresUser: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
