{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service-core.container-secret") -}}
{{- define "ffc-demo-payment-service-core.container-secret" -}}
data:
ConnectionStrings__DefaultConnection: {{ .Values.postgresService.postgresConnectionString | b64enc | quote }}
{{- end -}}