apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-developer-1-admin-rolebinding
  namespace: {{ .Values.namespace }}
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.workstream }}-developer-1
