{{- if .Values.postgresExternalName }}
{{- include "ffc-helm-library.service" (list . "ffc-demo-payment-service-core.postgres-service") -}}
{{- end }}
{{- define "ffc-demo-payment-service-core.postgres-service" -}}
{{- end -}}



