{{- if .Values.postgresExternalName }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.postgresHost }}
  labels:
    environment: {{ quote .Values.environment }}
spec:
  type: ExternalName
  externalName: {{ quote .Values.postgresExternalName }}
  ports:
    - name: port
      port: {{ .Values.postgresPort }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.name }}
  labels:
    app: {{ quote .Values.name }}
    environment: {{ quote .Values.environment }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ quote .Values.name }}
  type: {{ quote .Values.service.type }}