{{- if .Values.serviceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ quote .Values.namespace }}
  name: {{ quote .Values.serviceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ quote .Values.serviceAccount.roleArn }}
{{- end }}
