apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: ffc-demo-payment-service-core
version: 1.0.0

readinessProbe:         
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
 
livenessProbe:         
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3