apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: ffc-demo-payment-service-core
version: 1.0.0

readinessProbe:
  httpGet:         
    path: /healthy
    port: 3007
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
 
livenessProbe:
  httpGet:         
    path: /healthz
    port: 3007
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3