environment: development
postgresConnectionString: Server=ffc-demo-payment-core-postgres;Port=5432;Database=ffc_demo_payments;User Id=postgres;Password=ppp;
# postgresExternalName is the external host name to which PostgreSQL
# requests should be forwarded. If empty, PostgreSQL is assumed to be
# within the cluster and accessible via postgresHost
postgresExternalName:
postgresHost: ffc-demo-payments-core-postgres
postgresPort: 5432
name: ffc-demo-payment-service-core
image: ffc-demo-payment-service-core
imagePullSecret:
service:
  type: ClusterIP
  port: 80
volumeMounts: 
  mountPath: /var/www/
  name: core-app-dir
container:
  port: 3007
  registry:
  tag: latest
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 40m
  limitMemory: 120Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 33
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  redeployOnChange: update this field to force a change
  restartPolicy: Always
  scheduleQueueName: schedule
  scheduleQueueEndpoint: http://ffc-demo-payment-message-queue:9324
  scheduleQueueUrl: http://ffc-demo-payment-message-queue:9324/queue/schedule
  scheduleQueueRegion: eu-west-2
  scheduleQueueAccessKeyId: elasticmq
  scheduleQueueSecretAccessKey: elasticmq
  scheduleCreateQueue: true
  paymentQueueName: payment
  paymentQueueEndpoint: http://ffc-demo-payment-message-queue:9324
  paymentQueueUrl: http://ffc-demo-payment-message-queue:9324/queue/payment
  paymentQueueRegion: eu-west-2
  paymentQueueAccessKeyId: elasticmq
  paymentQueueSecretAccessKey: elasticmq
  paymentCreateQueue: true
  serviceAccountName: ffc-demo-payment-service-account
  replicaCount: 1
  comPlusEnableDiagnostics: 0
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
readinessProbe:
  path: /healthy
  port: 3007
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 10
livenessProbe:
  path: /healthz
  port: 3007
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 10
serviceAccount:
  name: ffc-demo-payment-service-account
  roleArn: arn:aws:iam::562955126301:role/ffc_demo_payment_service_role_001
