environment: development
name: ffc-demo-payment-service-core
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-payment-service-core

labels: {}

azureIdentity:
  resourceID: dummy
  clientID: dummy

appInsights:
  key:

containerConfigMap:
  name: ffc-demo-payment-service-core-config-map

containerSecret:
  name: ffc-demo-payment-service-core-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 40m
  limitMemory: 120Mi
  limitCpu: 80m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3007
  scheduleQueueAddress: schedule
  paymentQueueAddress: payment
  messageQueueHost: servicebus
  messageQueuePreFetch: 1
  comPlusEnableDiagnostics: 0

postgresService:
  postgresHost: ffc-demo-payments-core-postgres
  postgresPort: 5432
  postgresExternalName:
  postgresUser: postgres
  postgresDb: ffc_demo_payments

readinessProbe:
  path: /healthy
  port: 3007
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3007
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3

volumeMounts:
  mountPath: /var/www/
  name: core-app-dir
