name: ffc-demo-payment-service-core
namespace: ffc-demo
image: ffc-demo-payment-service-core

labels: {}

deployment:
  priorityClassName: low
  minReadySeconds: 5

container:
  port: 3007
  memCpuTier: M

readinessProbe:
  path: /healthy
  port: 3007
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3007
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3

volumeMounts:
  mountPath: /var/www/
  name: core-app-dir
