parameters:

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref:  refs/heads/rv/230880-CIPipeline
    - repository: _self
      name: DEFRA/ffc-demo-payment-service-core
      endpoint: DEFRA
      type: github
      ref: refs/heads/rv/230880-CIPipeline

extends:
  template: pipelines/common-app-build.yaml@ADPPipelineCommon
  parameters:
    projectName: 'FFC-DEMO-PAYMENT-SERVICE-CORE'
    deployFromFeature: false    
    appFrameworkType: 'DotNet6'
    appBuildConfig: 
      - buildConfiguration: 'Release'
        frameworkVersion: '6.x'      
        projectPath: '**/*.csproj'
        testProjectPath: '**/*.Tests.csproj'
        imageVersion: '0.1.0'
        chartVersion: '1.0.0'
        imageRepoName: 'ffc-demo-payment-service-core'


