- key: MESSAGE_QUEUE_HOST
  value: "TSTADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "tstadpdbsps1401.postgres.database.azure.com" 
- key: POSTGRES_USERNAME
  value: "tstadpinfmi1401-ffc-demo-payment-service" 