- key: MESSAGE_QUEUE_HOST
  value: "TSTADPINFSB2401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "tstadpdbsps2401.postgres.database.azure.com" 
- key: POSTGRES_USERNAME
  value: "tstadpinfmi2401-ffc-demo-payment-service"