- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB1401.servicebus.windows.net" 
- key: POSTGRES_HOST
  value: "sndadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "sndadpinfmi1401-ffc-demo-payment-service"
