- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB2401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "sndadpdbsps2401.postgres.database.azure.com" 
- key: POSTGRES_USERNAME
  value: "sndadpinfmi2401-ffc-demo-payment-service" 