- key: MESSAGE_QUEUE_HOST
  value: "PRDADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "prdadpdbsps1401.postgres.database.azure.com" 
- key: POSTGRES_USERNAME
  value: "prdadpinfmi1401-ffc-demo-payment-service"