- key: PAYMENT_TOPIC_ADDRESS
  value: "ffc-demo-payment"
- key: PAYMENT_SUBSCRIPTION_ADDRESS
  value: "ffc-demo-payment-payment-core"
- key: SCHEDULE_TOPIC_ADDRESS
  value: "ffc-demo-schedule" 
- key: SCHEDULE_SUBSCRIPTION_ADDRESS
  value: "ffc-demo-schedule-payment-core"  
- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB1401.servicebus.windows.net"  
- key: POSTGRES_DB
  value: "ffc_demo_payments"
- key: POSTGRES_HOST
  value: "sndadpdbsps1401.postgres.database.azure.com"  
- key: POSTGRES_PORT
  value: "5432"  
- key: POSTGRES_SCHEMA_NAME
  value: "public"
- key: POSTGRES_USERNAME
  value: "sndadpinfmid1401-ffc-demo-services"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}" 
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"