- key: PAYMENT_TOPIC_ADDRESS
  value: "fcp-demo-payment"
- key: PAYMENT_SUBSCRIPTION_ADDRESS
  value: "fcp-demo-payment-payment-core"
- key: SCHEDULE_TOPIC_ADDRESS
  value: "fcp-demo-schedule" 
- key: SCHEDULE_SUBSCRIPTION_ADDRESS
  value: "fcp-demo-schedule-payment-core"  
- key: POSTGRES_DB
  value: "fcp-demo-payments"
- key: POSTGRES_PORT
  value: "5432"  
- key: POSTGRES_SCHEMA_NAME
  value: "public"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}" 
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"